services:
  web:
    container_name: dev-ramadan-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/.cache
      - /app/build
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/db"
      JWT_SECRET: "secret"

  db:
    image: postgres:16
    container_name: dev-ramadan-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - ./storage/db-data:/var/lib/postgresql/data
