services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/.cache
      - /app/build
